### ISSUE TITLE
Build error on project using kotlin version 1.7.10

### ISSUE THREAD

**Issue by Ali-Farhoud** [PostHog/posthog-android#103]
### Description

implementation("com.posthog:posthog-android:3.+") is causing the build error this :.gradle/caches/transforms-3/2e83842a3dca5618ece679a149e8fbde/transformed/jetified-okio-jvm-3.6.0.jar!/META-INF/okio.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

**Comment by marandaneto** [comment]
A quick workaround for now is to use Kotlin 1.8.x

`id("org.jetbrains.kotlin.android") version "1.8.22" apply false`

You can still compile against Kotlin 1.7.x compatibility by doing this:

```
    compileOptions {
        sourceCompatibility = ...
        targetCompatibility = ...
    }
    kotlinOptions {
        jvmTarget = ...
        languageVersion = "1.7"
        apiVersion = "1.7"
    }
```

I'm looking into it, the problem is that we use okhttp, okhttp depends on okio, and we cannot control the version they are compiled against, lets me check if downgrading okhttp does not break anything.

**Comment by marandaneto** [comment]
Another option is to keep using Kotlin 1.7.x but do this:

```
    kotlinOptions {
        jvmTarget = ...
        freeCompilerArgs += "-Xskip-metadata-version-check"
    }
```

But this config [will be removed](https://github.com/gradle/gradle/issues/26810) in the next major version.

**Comment by marandaneto** [comment]
We compile the SDK against Kotlin 1.6

See the code snippet here https://github.com/PostHog/posthog-android/blob/25c5bcd393ccfab2862c576174962c1303e8b22d/buildSrc/src/main/java/PostHogKotlinConfig.kt#L5-L7

and here https://github.com/PostHog/posthog-android/blob/25c5bcd393ccfab2862c576174962c1303e8b22d/buildSrc/src/main/java/PosthogBuildConfig.kt#L30

It's just the metadata appended in the library, so I expect that everything should work as it is, still investigating how to avoid that.

Using the latest version of the tooling is recommended because it has enhancements and fixes, but the final generated bytecode is still Kotlin 1.6 compatible.
