### ISSUE TITLE
java.lang.InstantiationError crash in prod during posthog init

### ISSUE THREAD

**Issue by alekseyrozh** [PostHog/posthog-android#135]
### Version

3.1.1

### Steps to Reproduce

This is firebase carshlytics report from a production app. It occasionally fails on startup due to the posthog crash. For a certain user it crashed 4 times in a row on this error

Android 10
Model:A5 2020
Brand:Oppo

### Expected Result

Not crash

### Actual Result

      Fatal Exception: java.lang.InstantiationError: F8.c
       at com.posthog.PostHog.setup(PostHog.java:66)
       at com.posthog.PostHog$Companion.setup(PostHog.java:648)
       at com.posthog.android.PostHogAndroid$Companion.setup(PostHogAndroid.java:42)
       at com.evelize.teleprompter.TeleprompterApplication.initPostHog(TeleprompterApplication.kt:128)
       at com.evelize.teleprompter.TeleprompterApplication.onCreate(TeleprompterApplication.kt:57)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1199)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6913)
       at android.app.ActivityThread.access$1600(ActivityThread.java:240)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7888)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:998)
       
       
Stack trace points here, that leaves me fairly confused
    
<img width="943" alt="Screenshot 2024-05-27 at 14 39 40" src="https://github.com/PostHog/posthog-android/assets/10654710/a13099be-f64f-4dc2-9dc9-659ea7bca0b8">

The way I call it from my code is:
<img width="647" alt="Screenshot 2024-05-27 at 14 40 55" src="https://github.com/PostHog/posthog-android/assets/10654710/67269b2c-5ddd-46ba-ae9d-2f49195daca7">

**Comment by marandaneto** [comment]
@alekseyrozh Yeah that is strange, do you minify your app?
the name F8.c seems to be something minified and minification affects line number so it's hard to tell where exactly it is.
There were a bunch of bug fixes tho since you are using 3.1.1, mind upgrading and checking out if this still happens in the newer version?

**Comment by marandaneto** [comment]
@alekseyrozh I did check and nothing was obvious.

Gson uses reflection but we do have the [shipped proguard rules](https://github.com/PostHog/posthog-android/blob/main/posthog-android/consumer-rules.pro).

So minify isn't a problem afaik, otherwise it'd be crashing for everyone.

We also didn't get any reports from anyone else related to `InstantiationError`.

Since you have the proguard mapping file so symbolicate and check the real names and line numbers.
Could you symbolicate the following lines:

>   Fatal Exception: java.lang.InstantiationError: F8.c
>    at com.posthog.PostHog.setup(PostHog.java:66)
>    at com.posthog.PostHog$Companion.setup(PostHog.java:648)
>    at com.posthog.android.PostHogAndroid$Companion.setup(PostHogAndroid.java:42)

So we know what exactly `F8.c` is and the line numbers? you can use https://www.guardsquare.com/manual/tools/retrace for that

**Comment by marandaneto** [comment]
@alekseyrozh What is the AGP version? what is the Gradle version? do you have the R8 full mode enabled?

**Comment by alekseyrozh** [comment]
@marandaneto from what I read R8 full mode is enabled by default: https://developer.android.com/build/shrink-code#full-mode. 

My setup if quite default:
```
          isMinifyEnabled = true
          isShrinkResources = true
          proguardFiles(
              getDefaultProguardFile("proguard-android-optimize.txt"),
              "proguard-rules.pro"
          )
```

and here is the list of plugin versions:
```
plugins {
    id("com.android.application") version "8.3.2" apply false
    id("com.android.library") version "8.3.2" apply false
    id("org.jetbrains.kotlin.android") version "1.9.23" apply false
    id("org.jetbrains.kotlin.plugin.serialization") version "1.9.23" apply false
    id("com.google.devtools.ksp") version "1.9.23-1.0.20" apply false
    id("com.google.gms.google-services") version "4.4.0" apply false
    id("com.google.firebase.crashlytics") version "2.9.9" apply false
}
```

**Comment by marandaneto** [comment]
@alekseyrozh full mode is enabled after AGP >= 8, and you are using 8.3.2 so indeed it is.
Please take a look at this [comment](https://github.com/PostHog/posthog-android/issues/135#issuecomment-2134511214), since I cannot reproduce this locally on my own, maybe with extra info, I can try again, thanks.

**Comment by alekseyrozh** [comment]
@marandaneto I tried retracing as you suggested, however in the output I saw the exact same stacktrace as I attached to this issue. Which made me realise that all other lines of code are actually using full classnames and correct line numbers. So the stack trace is actually referring to the original source code, just not the error message itself. I'm not very familiar with this procedure, so I might have missed smth. Please let me know if so

<img width="865" alt="Screenshot 2024-06-08 at 23 16 36" src="https://github.com/PostHog/posthog-android/assets/10654710/36e2a6a8-c147-4e18-8cf1-942cdc37a50f">

**Comment by marandaneto** [comment]
@alekseyrozh the issue is the `F8.c` which would tell what's the error about.
I don't see how https://github.com/PostHog/posthog-android/blob/6eadf9b95f4904fd067000235dd9eaeb891dac43/posthog/src/main/java/com/posthog/PostHog.kt#L66 would throw `InstantiationError`, so I wonder if the `minifyEnabled` messed up the line numbers.

**Comment by marandaneto** [comment]
Maybe I found a possible problem https://github.com/PostHog/posthog-android/pull/140
