### ISSUE TITLE
screen_name is not set on $screen events - Using compose

### ISSUE THREAD

**Issue by curliq** [PostHog/posthog-android#150]
### Version

3.4.2

### Steps to Reproduce

1. Initialise posthog in the application onCreate:
```
val config = PostHogAndroidConfig(
    apiKey = BuildConfig.ANDROID_KEY_POSTHOG,
    host = "https://eu.i.posthog.com",
    captureScreenViews = true,
    captureApplicationLifecycleEvents = true,
).apply {
    sessionReplay = false
    debug = BuildConfig.DEBUG
}
PostHogAndroid.setup(this, config)
```
3. Start an Activity (AppCompatActivity) with startActivity(Intent)
4. Start more activities

### Expected Result

$screen events logged for each activity with `screen_name` being the `Activity::class.java.name` or something related to the activity opened

### Actual Result

$screen events logged for each activity with `screen_name` being the value from `rootProject.name = ...` in the root `settings.gradle.kts` file

I'm using multiple activities all with compose inside them.

Please let me know if more info is needed to reproduce

**Comment by marandaneto** [comment]
@curliq thanks for the issue.

Sadly this is an issue with Compose, since the classes are wrapped/autogenerated, not sure if there's a way to do this correctly when using compose.

See what we do here https://github.com/PostHog/posthog-android/blob/c6a5fc6196da76366d3851b28d2e196aa65b1afc/posthog-android/src/main/java/com/posthog/android/internal/PostHogAndroidUtils.kt#L125-L134

Any ideas on how to get this right for Compose if possible at all?

I know we could offer a way for you to annotate the Compose screens with an annotation but we don't offer this feature yet.
Another option, for now, is to deactivate the `captureScreenViews` option and [capture screen events manually](https://posthog.com/docs/libraries/android#capturing-screen-views).

**Comment by marandaneto** [comment]
The order of `loadLabel` is:
`android:label` from the Activity.
If not defined, `android:label`, from the `application` tag.
Otherwise the Activity class name (absolute such as `com.posthog.android.sample.MainActivity`) so there's no fallback needed since this is by design already.

> This ensures that the activityLabel method will only return a label if it is explicitly defined for the Activity, avoiding returning the Application's label by mistake.

This makes sense, I'd love a PR for that.

**Comment by thisames** [comment]
I'm a little confused now, according to this doc, is it correct to return the android:label of the <application> if the android:label of the <activity> is not defined?

So there is no issue, correct? Everything is going as it should

**Comment by marandaneto** [comment]
> I'm a little confused now, according to this doc, is it correct to return the android:label of the `<application>` if the android:label of the `<activity>` is not defined?
> 
> So there is no issue, correct? Everything is going as it should

nope, I'd say it's wrong, this is the current state, happy to remove that part once you make a PR and its released.
it's a side effect of `loadLabel` I was not aware of.

**Comment by thisames** [comment]
> > I'm a little confused now, according to this doc, is it correct to return the android:label of the `<application>` if the android:label of the `<activity>` is not defined?
> > So there is no issue, correct? Everything is going as it should
> 
> nope, I'd say it's wrong, this is the current state, happy to remove that part once you make a PR and its released. it's a side effect of `loadLabel` I was not aware of.

Please confirm whether it will be necessary to keep adding `activityName` method.

https://github.com/thisames/posthog-android/commit/b12bf287ec49e296ae0c4a44c524ec706d4adc55

or do I just keep the new functionality of `activityLabel` method

**Comment by marandaneto** [comment]
@thisames left a few comments otherwise all good.
