### ISSUE TITLE
Note that observation on multiple threads in layout/draw is not supported. Make sure your measure/layout/draw for each Owner (AndroidComposeView) is executed on the same thread

### ISSUE THREAD

**Issue by xemniz** [PostHog/posthog-android#203]
### Version

3.9.0

### Steps to Reproduce

1. I use compose in fragments a lot 
2. It's really ocassional but im just switching tab bars, scrolling lazylists
3. App just crashes
4. previousThreadName from the stacktrace is PostHogReplayThread
5. when i switch off the replay, can't reproduce this

### Expected Result

App works

### Actual Result

java.lang.IllegalArgumentException: Detected multithreaded access to  : previousThreadId=158), currentThread={id=2, name=main}. Note that observation on multiple threads in layout/draw is not supported. Make sure your measure/layout/draw for each Owner (AndroidComposeView) is executed on the same thread.
                                                                                                    	at androidx.compose.runtime.PreconditionsKt.throwIllegalArgumentException(Preconditions.kt:26)
                                                                                                    	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:708)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:133)
                                                                                                    	at androidx.compose.ui.node.OwnerSnapshotObserver.observeMeasureSnapshotReads$ui_release(OwnerSnapshotObserver.kt:113)

**Comment by marandaneto** [comment]
Hello @xemniz thanks for the issue.
Are you using the screenshot or wireframe mode?
Which SDK version?
We don't call `measure` and `layout` at all but we do use `draw` [here](https://github.com/PostHog/posthog-android/blob/d9052d0232d79211c73b2f5fd972e4e5efac2b27/posthog-android/src/main/java/com/posthog/android/replay/PostHogReplayIntegration.kt#L1231) which should not be a problem anyway.
Can you provide a minimal reproducible example? I tried using a compose-sample app but did not succeed in reproducing the issue.

**Comment by xemniz** [comment]
<img width="485" alt="image" src="https://github.com/user-attachments/assets/adfd197f-8c26-4ed5-b9b2-6ad95a07f0b6">
this commented lines made a difference, it was reproducible in all my screens, but randomly i'd say. in crashlytics crashfree sessions dropped to 65 percent with 3.9.0 version of posthog.

<img width="834" alt="image" src="https://github.com/user-attachments/assets/cf5fc03a-7e93-440f-b5de-8136e102968f">
right here i checked thread names and the one that's not [main] was PostHogReplayThread and thet's the place where android framework does this check that throws an error

**Comment by marandaneto** [comment]
@xemniz `getAllSemanticsNodes` is called within a try/catch, so `IllegalArgumentException` should not have crashed the app, looking into this though.

**Comment by marandaneto** [comment]
@xemniz what's the version of your resolved `androidx.compose.ui:ui`?

**Comment by xemniz** [comment]
androidx.compose:compose-bom:2024.10.00 - compose version

**Comment by xemniz** [comment]
> @xemniz `getAllSemanticsNodes` is called within a try/catch, so `IllegalArgumentException` should not have crashed the app, looking into this though.

yes, but having crash not in PostHogSdk code, but in `androidx.compose.runtime.snapshots.SnapshotStateObserver`, so try catch won't help 

<img width="752" alt="image" src="https://github.com/user-attachments/assets/07bd6c0d-a4d6-417c-95d8-98f670f8b0a8">

**Comment by marandaneto** [comment]
Session replay tries to do as much as possible off of the main thread because of performance reasons, so the replay thread calls that function.
What we could do is:

```
            val latch = CountDownLatch(1)

            var semanticsNodes: List<SemanticsNode>? = null
            mainHandler.handler.post {
                try {
                    semanticsNodes = semanticsOwner.getAllSemanticsNodes(true)
                } catch (e: Throwable) {
                    config.logger.log("Session Replay getAllSemanticsNodes failed: $e")
                } finally {
                    latch.countDown()
                }
            }

            latch.await(1000, TimeUnit.MILLISECONDS)
```

So only that part will be accessed via the main thread, unless `(view as? RootForTest)?.semanticsOwner`, `node.config`, and `node.boundsInWindow` require main thread which I am trying to figure out.
I can't reproduce this issue yet so I can't verify that.

**Comment by marandaneto** [comment]
@beradeep did you see this one, any ideas?

**Comment by beradeep** [comment]
@marandaneto I looked into it just a bit, turns out I was able to reproduce the issue. But its occurrence is unpredictable. It came up a couple of times when I ran a sample app repeatedly for at least 10 times.

**Comment by marandaneto** [comment]
> @marandaneto I looked into it just a bit, turns out I was able to reproduce the issue. But its occurrence is unpredictable. It came up a couple of times when I ran a sample app repeatedly for at least 10 times.

Thanks, can you share the sample app you tried? So I can try to reproduce it myself as well.
Can you try if a solution [like this](https://github.com/PostHog/posthog-android/issues/203#issuecomment-2457567039) would help?
Would be cool to at least narrow down which function call (if 1 or N) is causing this, maybe only `getAllSemanticsNodes` isn't enough.
Maybe this started after a specific compose version, etc.

Any help here is appreciated since I cannot reproduce the issue at all.

**Comment by beradeep** [comment]
@marandaneto I faced the issue in the app startup, so I think it is practically possible with any compose app, although I only tried with [`androidx.compose:compose-bom:2024.10.00`](https://github.com/PostHog/posthog-android/issues/203#issuecomment-2457549139). I used [this app](https://github.com/beradeep/whitehole/releases/tag/v0.7).

The google issuetracker [comment](https://issuetracker.google.com/issues/319395743#comment11) also mentions that they always call `getAllSemanticNodes` on the ui thread, as I later found [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-test/src/commonMain/kotlin/androidx/compose/ui/test/TestOwner.kt;l=79) too. So I think this might be because we are calling it outside of the ui thread, and so [this](https://github.com/PostHog/posthog-android/issues/203#issuecomment-2457567039) might solve the issue.

**Comment by beradeep** [comment]
But as [this](https://issuetracker.google.com/issues/319395743#comment14) comment mentions, the properties that we use i.e. `node.boundsInWindow` and `node.config` might not thread safe too :(

**Comment by marandaneto** [comment]
@beradeep https://github.com/PostHog/posthog-android/pull/204
I think this should help, mind testing after release? thx.

**Comment by marandaneto** [comment]
https://github.com/PostHog/posthog-android/releases/tag/3.9.1
Might take a few minutes until the version is available on maven central.
Let us know if that helps.

**Comment by beradeep** [comment]
> @beradeep #204 I think this should help, mind testing after release? thx.

Reran the same app for a number times on both `3.9.0` and `3.9.1`. Crashed 5 times on the former, but none on the latter. LGTM!

**Comment by zhuziwei0408** [comment]
> So in this case the whole block should be executed in the main thread.

The entire logic such as getAllSemanticsNodes is put into the main thread for execution. Have you ever encountered a situation where the execution is very slow and the main thread is stuck? I tested that getting SemanticsNodes in the main thread would cause a hang.
